export const languages = [
  //   { label: "Abkhazian", code: "ab" },
  //   { label: "Afar", code: "aa" },
  //   { label: "Afrikaans", code: "af" },
  //   { label: "Akan", code: "ak" },
  //   { label: "Albanian", code: "sq" },
  //   { label: "Amharic", code: "am" },
  //   { label: "Arabic", code: "ar" },
  //   { label: "Aragonese", code: "an" },
  //   { label: "Argentina", code: "es-ar" },
  //   { label: "Armenian", code: "hy" },
  //   { label: "Assamese", code: "as" },
  //   { label: "Avaric", code: "av" },
  //   { label: "Avestan", code: "ae" },
  //   { label: "Aymara", code: "ay" },
  //   { label: "Azerbaijani", code: "az" },
  //   { label: "Bambara", code: "bm" },
  //   { label: "Bashkir", code: "ba" },
  //   { label: "Basque", code: "eu" },
  //   { label: "Belarusian", code: "be" },
  //   { label: "Bengali (Bangla)", code: "bn" },
  //   { label: "Bihari", code: "bh" },
  //   { label: "Bislama", code: "bi" },
  //   { label: "Bosnian", code: "bs" },
  //   { label: "Breton", code: "br" },
  //   { label: "Bulgarian", code: "bg" },
  //   { label: "Burmese", code: "my" },
  //   { label: "Catalan", code: "ca" },
  //   { label: "Chamorro", code: "ch" },
  //   { label: "Chechen", code: "ce" },
  //   { label: "Chichewa, Chewa, Nyanja", code: "ny" },
  //   { label: "Chinese", code: "zh" },
  //   { label: "Chinese (Simplified)", code: "zh-Hans" },
  //   { label: "Chinese (Traditional)", code: "zh-Hant" },
  //   { label: "Chuvash", code: "cv" },
  //   { label: "Cornish", code: "kw" },
  //   { label: "Corsican", code: "co" },
  //   { label: "Cree", code: "cr" },
  //   { label: "Croatian", code: "hr" },
  //   { label: "Czech", code: "cs" },
  //   { label: "Danish", code: "da" },
  //   { label: "Divehi, Dhivehi, Maldivian", code: "dv" },
  //   { label: "Dutch", code: "nl" },
  //   { label: "Dzongkha", code: "dz" },
  { label: "English", code: "en", apiValue: 1 },
  //   { label: "Esperanto", code: "eo" },
  //   { label: "Estonian", code: "et" },
  //   { label: "Ewe", code: "ee" },
  //   { label: "Faroese", code: "fo" },
  //   { label: "Fijian", code: "fj" },
  //   { label: "Finnish", code: "fi" },
  { label: "French", code: "fr", apiValue: 4 },
  //   { label: "Fula, Fulah, Pulaar, Pular", code: "ff" },
  //   { label: "Galician", code: "gl" },
  //   { label: "Gaelic (Scottish)", code: "gd" },
  //   { label: "Gaelic (Manx)", code: "gv" },
  //   { label: "Georgian", code: "ka" },
  //   { label: "German", code: "de" },
  //   { label: "Greek", code: "el" },
  //   { label: "Greenlandic", code: "kl" },
  //   { label: "Guarani", code: "gn" },
  //   { label: "Gujarati", code: "gu" },
  //   { label: "Haitian Creole", code: "ht" },
  //   { label: "Hausa", code: "ha" },
  //   { label: "Hebrew", code: "he" },
  //   { label: "Herero", code: "hz" },
  //   { label: "Hindi", code: "hi" },
  //   { label: "Hiri Motu", code: "ho" },
  //   { label: "Hungarian", code: "hu" },
  //   { label: "Icelandic", code: "is" },
  //   { label: "Ido", code: "io" },
  //   { label: "Igbo", code: "ig" },
  //   { label: "Indonesian", code: "id, in" },
  //   { label: "Interlingua", code: "ia" },
  //   { label: "Interlingue", code: "ie" },
  //   { label: "Inuktitut", code: "iu" },
  //   { label: "Inupiak", code: "ik" },
  //   { label: "Irish", code: "ga" },
  //   { label: "Italian", code: "it" },
  //   { label: "Japanese", code: "ja" },
  //   { label: "Javanese", code: "jv" },
  //   { label: "Kalaallisut, Greenlandic", code: "kl" },
  //   { label: "Kannada", code: "kn" },
  //   { label: "Kanuri", code: "kr" },
  //   { label: "Kashmiri", code: "ks" },
  //   { label: "Kazakh", code: "kk" },
  //   { label: "Khmer", code: "km" },
  //   { label: "Kikuyu", code: "ki" },
  //   { label: "Kinyarwanda (Rwanda)", code: "rw" },
  //   { label: "Kirundi", code: "rn" },
  //   { label: "Kyrgyz", code: "ky" },
  //   { label: "Komi", code: "kv" },
  //   { label: "Kongo", code: "kg" },
  //   { label: "Korean", code: "ko" },
  //   { label: "Kurdish", code: "ku" },
  //   { label: "Kwanyama", code: "kj" },
  //   { label: "Lao", code: "lo" },
  //   { label: "Latin", code: "la" },
  //   { label: "Latvian (Lettish)", code: "lv" },
  //   { label: "Limburgish ( Limburger)", code: "li" },
  //   { label: "Lingala", code: "ln" },
  //   { label: "Lithuanian", code: "lt" },
  //   { label: "Luga-Katanga", code: "lu" },
  //   { label: "Luganda, Ganda", code: "lg" },
  //   { label: "Luxembourgish", code: "lb" },
  //   { label: "Manx", code: "gv" },
  //   { label: "Macedonian", code: "mk" },
  //   { label: "Malagasy", code: "mg" },
  //   { label: "Malay", code: "ms" },
  //   { label: "Malayalam", code: "ml" },
  //   { label: "Maltese", code: "mt" },
  //   { label: "Maori", code: "mi" },
  //   { label: "Marathi", code: "mr" },
  //   { label: "Marshallese", code: "mh" },
  //   { label: "Moldavian", code: "mo" },
  //   { label: "Mongolian", code: "mn" },
  //   { label: "Nauru", code: "na" },
  //   { label: "Navajo", code: "nv" },
  //   { label: "Ndonga", code: "ng" },
  //   { label: "Northern Ndebele", code: "nd" },
  //   { label: "Nepali", code: "ne" },
  //   { label: "Norwegian", code: "no" },
  //   { label: "Norwegian bokmål", code: "nb" },
  //   { label: "Norwegian nynorsk", code: "nn" },
  //   { label: "Nuosu", code: "ii" },
  //   { label: "Occitan", code: "oc" },
  //   { label: "Ojibwe", code: "oj" },
  //   { label: "Old Church Slavonic, Old Bulgarian", code: "cu" },
  //   { label: "Oriya", code: "or" },
  //   { label: "Oromo (Afaan Oromo)", code: "om" },
  //   { label: "Ossetian", code: "os" },
  //   { label: "Pāli", code: "pi" },
  //   { label: "Pashto, Pushto", code: "ps" },
  //   { label: "Persian (Farsi)", code: "fa" },
  //   { label: "Polish", code: "pl" },
  //   { label: "Portuguese", code: "pt" },
  //   { label: "Punjabi (Eastern)", code: "pa" },
  //   { label: "Quechua", code: "qu" },
  //   { label: "Romansh", code: "rm" },
  //   { label: "Romanian", code: "ro" },
  { label: "Russian", code: "ru", apiValue: 3 },
  //   { label: "Sami", code: "se" },
  //   { label: "Samoan", code: "sm" },
  //   { label: "Sango", code: "sg" },
  //   { label: "Sanskrit", code: "sa" },
  //   { label: "Serbian", code: "sr" },
  //   { label: "Serbo-Croatian", code: "sh" },
  //   { label: "Sesotho", code: "st" },
  //   { label: "Setswana", code: "tn" },
  //   { label: "Shona", code: "sn" },
  //   { label: "Sichuan Yi", code: "ii" },
  //   { label: "Sindhi", code: "sd" },
  //   { label: "Sinhalese", code: "si" },
  //   { label: "Siswati", code: "ss" },
  //   { label: "Slovak", code: "sk" },
  //   { label: "Slovenian", code: "sl" },
  //   { label: "Somali", code: "so" },
  //   { label: "Southern Ndebele", code: "nr" },
  { label: "Spanish", code: "es", apiValue: 2 },
  //   { label: "Sundanese", code: "su" },
  //   { label: "Swahili (Kiswahili)", code: "sw" },
  //   { label: "Swati", code: "ss" },
  //   { label: "Swedish", code: "sv" },
  //   { label: "Tagalog", code: "tl" },
  //   { label: "Tahitian", code: "ty" },
  //   { label: "Tajik", code: "tg" },
  //   { label: "Tamil", code: "ta" },
  //   { label: "Tatar", code: "tt" },
  //   { label: "Telugu", code: "te" },
  //   { label: "Thai", code: "th" },
  //   { label: "Tibetan", code: "bo" },
  //   { label: "Tigrinya", code: "ti" },
  //   { label: "Tonga", code: "to" },
  //   { label: "Tsonga", code: "ts" },
  //   { label: "Turkish", code: "tr" },
  //   { label: "Turkmen", code: "tk" },
  //   { label: "Twi", code: "tw" },
  //   { label: "Uyghur", code: "ug" },
  //   { label: "Ukrainian", code: "uk" },
  //   { label: "Urdu", code: "ur" },
  //   { label: "Uzbek", code: "uz" },
  //   { label: "Venda", code: "ve" },
  //   { label: "Vietnamese", code: "vi" },
  //   { label: "Volapük", code: "vo" },
  //   { label: "Wallon", code: "wa" },
  //   { label: "Welsh", code: "cy" },
  //   { label: "Wolof", code: "wo" },
  //   { label: "Western Frisian", code: "fy" },
  //   { label: "Xhosa", code: "xh" },
  //   { label: "Yiddish", code: "yi" },
  //   { label: "Yoruba", code: "yo" },
  //   { label: "Zhuang, Chuang", code: "za" },
  //   { label: "Zulu", code: "zu" },
];
